name: Mocha Tests on Windows

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch: # 👈 Enables manual trigger

jobs:
  test:
    runs-on: windows-latest # Runs on Windows

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci # Ensures a clean installation

      - name: Run Mocha Tests with Spec Reporter
        run: |
          npx mocha --timeout 10000 "GroceryApi\\groceryStore\\groceryApi.js" --reporter spec
